import JSZip from "jszip";
import type { AgentDraft, AgentManifest } from "./types";

export const ZERO_G_ROUTER_URL = "https://router-api.0g.ai/v1";

export const starterAgent: AgentDraft = {
  name: "0G Research Scout",
  description:
    "A portable OpenClaw-style agent that researches a topic, reasons through 0G Compute, and persists memory/log artifacts to 0G Storage.",
  soul:
    "You are 0G Research Scout, a focused research assistant. You prefer concise answers, cite evidence, and write durable memories after important findings.",
  memory:
    "# Long-term Memory\n\n- This agent was generated by ClawBuilder 0G.\n- Use 0G Compute as the default OpenAI-compatible inference router.\n- Mirror important conclusions and run logs to 0G Storage.",
  model: {
    providerName: "0g",
    apiBase: ZERO_G_ROUTER_URL,
    modelId: "openai/gpt-oss-20b",
    apiKeyEnv: "OG_API_KEY",
  },
  skills: [
    {
      id: "0g-compute",
      name: "0g-compute",
      description: "Route OpenAI-compatible chat completions through the 0G Compute router.",
      enabled: true,
    },
    {
      id: "0g-storage-memory",
      name: "0g-storage-memory",
      description: "Package agent files, memory, and run logs for upload to 0G Storage.",
      enabled: true,
    },
    {
      id: "evidence-summarizer",
      name: "evidence-summarizer",
      description: "Turn raw notes into citation-friendly summaries.",
      enabled: true,
    },
  ],
  workflow: [
    {
      id: "collect",
      title: "Collect context",
      instruction: "Ask for missing constraints, then gather source material and current memory.",
    },
    {
      id: "reason",
      title: "Reason with 0G Compute",
      instruction: "Send the prompt to the configured 0G OpenAI-compatible provider.",
    },
    {
      id: "persist",
      title: "Persist memory",
      instruction: "Append durable decisions to MEMORY.md and publish package/log roots to 0G Storage.",
    },
  ],
  storage: {
    packageUri: "0g://package/{rootHash}",
    memoryUri: "0g://memory/{agentId}/MEMORY.md",
    logUri: "0g://logs/{agentId}/{sessionId}.jsonl",
  },
};

export function createManifest(agent: AgentDraft): AgentManifest {
  const enabledSkills = agent.skills.filter((skill) => skill.enabled);

  return {
    schema: "clawbuilder.0g.agent.v1",
    name: agent.name,
    description: agent.description,
    provider: {
      name: agent.model.providerName,
      apiBase: agent.model.apiBase,
      apiType: "openai-chat",
      authType: "bearer-token",
      apiKeyEnv: agent.model.apiKeyEnv,
      models: [
        {
          id: agent.model.modelId,
          name: agent.model.modelId,
          input: ["text"],
          contextWindow: 128000,
          maxTokens: 8192,
        },
      ],
    },
    files: ["agent.json", "SOUL.md", "MEMORY.md", "workflow.json"],
    skills: enabledSkills.map((skill) => ({
      name: skill.name,
      description: skill.description,
      path: `skills/${skill.name}/SKILL.md`,
    })),
    workflow: agent.workflow,
    storage: {
      network: "0g-storage",
      packageUri: agent.storage.packageUri,
      memoryUri: agent.storage.memoryUri,
      logUri: agent.storage.logUri,
    },
  };
}

export function createAgentConfig(agent: AgentDraft) {
  return {
    name: agent.name,
    description: agent.description,
    model: `${agent.model.providerName}/${agent.model.modelId}`,
    providers: {
      [agent.model.providerName]: {
        apiBase: agent.model.apiBase,
        apiKey: `env:${agent.model.apiKeyEnv}`,
        apiType: "openai-chat",
        authType: "bearer-token",
        models: [
          {
            id: agent.model.modelId,
            name: agent.model.modelId,
            input: ["text"],
            contextWindow: 128000,
            maxTokens: 8192,
          },
        ],
      },
    },
    storage: createManifest(agent).storage,
  };
}

export function skillMarkdown(skillName: string, description: string): string {
  if (skillName === "0g-compute") {
    return `---\nname: 0g-compute\ndescription: Route agent inference through 0G Compute's OpenAI-compatible router.\nenv:\n  - OG_API_KEY\n---\n\n# 0G Compute\n\nUse the configured OpenAI-compatible provider:\n\n- Base URL: ${ZERO_G_ROUTER_URL}\n- API key: \`env:OG_API_KEY\`\n- Auth: bearer token\n\nGenerated agents should call the normal chat-completions interface so they remain portable across FastClaw, GoClaw, and OpenClaw-style runtimes.\n`;
  }

  if (skillName === "0g-storage-memory") {
    return `---\nname: 0g-storage-memory\ndescription: Publish agent packages, MEMORY.md snapshots, and run logs to 0G Storage.\nenv:\n  - OG_STORAGE_PRIVATE_KEY\n  - OG_STORAGE_RPC_URL\n  - OG_STORAGE_INDEXER\n---\n\n# 0G Storage Memory\n\nPackage these files before upload:\n\n- agent.json\n- SOUL.md\n- MEMORY.md\n- workflow.json\n- skills/**/SKILL.md\n\nUpload flow:\n\n1. Create a file/blob package.\n2. Generate its 0G Storage Merkle root.\n3. Upload through the 0G Storage indexer.\n4. Store the returned root in \`manifest.0g.json\`.\n`;
  }

  return `---\nname: ${skillName}\ndescription: ${description}\n---\n\n# ${skillName}\n\n${description}\n`;
}

export async function buildAgentZip(agent: AgentDraft): Promise<Blob> {
  const zip = new JSZip();
  const enabledSkills = agent.skills.filter((skill) => skill.enabled);

  zip.file("agent.json", JSON.stringify(createAgentConfig(agent), null, 2));
  zip.file("SOUL.md", `# Soul\n\n${agent.soul}\n`);
  zip.file("MEMORY.md", agent.memory.endsWith("\n") ? agent.memory : `${agent.memory}\n`);
  zip.file("workflow.json", JSON.stringify(agent.workflow, null, 2));
  zip.file("manifest.0g.json", JSON.stringify(createManifest(agent), null, 2));
  zip.file(
    "README.md",
    `# ${agent.name}\n\n${agent.description}\n\n## Run\n\nSet \`${agent.model.apiKeyEnv}\`, then point any OpenAI-compatible agent runtime at \`${agent.model.apiBase}\` with model \`${agent.model.modelId}\`.\n`,
  );

  for (const skill of enabledSkills) {
    zip.file(`skills/${skill.name}/SKILL.md`, skillMarkdown(skill.name, skill.description));
  }

  return zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
